### ISSUE TITLE
add info on how to use extension

### ISSUE THREAD

**Issue by TekBear** [konkon1234/remember-form-inputs#1]
It is unclear how to use this.

I was looking for something that works like firefox "form history control" add on it will log all form data and editor input box data used on a page  to a database time stamped  so I can salvage data when a browser crash or form submit fails.

- What is store key ?
- What is number of elements saved referring to is it form fields?
- Is it saving automatically or just manual press icon on tool bar?
- When I come back to a page previous data saved is not available but if I give it a meaningful name I can find it explicitly - this works for some pages
- Is data save stored in a static file %systemdrive%\%USERPROFILE%\local settings\Application Data\Google\Chrome\User Data\Default\Local Extension Settings\fc*hl\000003.log" or does the name change over time?

**Comment by konkon1234** [comment]
It is unclear how to use this.

I was looking for something that works like firefox "form history control" add on it will log all form data and editor input box data used on a page to a database time stamped so I can salvage data when a browser crash or form submit fails.

> What is store key ?

The store key is a unique key for storing the form contents. It is like a file name. The default value is simply md5 of url. You can change it to a free value.

> What is number of elements saved referring to is it form fields?

The values of input, textarea, and select tags are saved. Some inputs are not saved by type, and those to be saved are defined below.

Https://github.com/konkon1234/remember-form-inputs/blob/master/remember-inputs.js#L4

> Is it saving automatically or just manual press icon on tool bar?

The contents entered at the timing when the store button is pushed are saved


> Is data save stored in a static file %systemdrive%%USERPROFILE%\local settings\Application Data\Google\Chrome\User Data\Default\Local Extension Settings\fc*hl\000003.log" or does the name change over time?

The data storage destination is hidden by the chrome extension API.
